/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  safelist: [
    'animate-gradient-move',
    'animate-float-slow',
    'animate-float-medium',
    'animate-float-fast',
    'animate-tech-line',
    'animate-tech-line2',
    'bg-gradient-to-br',
    'from-[#1a79f6]',
    'via-[#0e2a47]',
    'to-[#0a1931]',
    'bg-blue-400',
    'bg-blue-600',
    'bg-cyan-400',
    'bg-blue-300',
    'bg-blue-500',
    'bg-blue-900',
    'bg-cyan-300',
    'bg-blue-400',
    'bg-blue-900',
    'rounded-full',
    'blur-2xl',
    'opacity-90',
    'opacity-30',
    'opacity-20',
    'opacity-10',
    'w-40',
    'h-40',
    'w-32',
    'h-32',
    'w-24',
    'h-24',
    'absolute',
    'inset-0',
    'top-1/4',
    'left-1/4',
    'top-2/3',
    'left-2/3',
    'top-1/2',
    'left-1/2',
    'left-0',
    'top-1/3',
    'w-full',
    'h-1',
    'right-0',
    'bottom-1/4',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#1a79f6',
      },
      screens: {
        'xs': '400px',
      },
    },
  },
  plugins: [],
};
